// Style reminder: data stays presentation-neutral so the Tactical Field Notes UI can emphasize names, sequence, and signal brass.

export type DotaEntry = {
  enemy: string;
  support: string[];
  core: string[];
  treasures: string[];
};

export const DOTA_DATA: DotaEntry[] = [
  { enemy: "Abaddon", support: ["Shadow Demon"], core: ["Slark"], treasures: ["Eul's Scepter of Divinity"] },
  { enemy: "Alchemist", support: ["Ancient Apparition"], core: ["Lifestealer"], treasures: ["Spirit Vessel"] },
  { enemy: "Ancient Apparition", support: ["Clockwerk"], core: ["Weaver"], treasures: ["Glimmer Cape", "Pipe of Insight"] },
  { enemy: "Anti-Mage", support: ["Shadow Shaman"], core: ["Meepo"], treasures: ["Orchid Malevolence", "Scythe of Vyse"] },
  { enemy: "Arc Warden", support: ["Bane"], core: ["Broodmother"], treasures: ["Gleipnir", "Orchid Malevolence"] },
  { enemy: "Axe", support: ["Viper"], core: ["Timbersaw"], treasures: ["Eul's Scepter of Divinity"] },
  { enemy: "Bane", support: ["Silencer"], core: ["Lycan"], treasures: ["Lotus Orb", "Linken's Sphere"] },
  { enemy: "Batrider", support: ["Abaddon"], core: ["Queen of Pain"], treasures: ["Lotus Orb", "Hurricane Pike"] },
  { enemy: "Beastmaster", support: ["Winter Wyvern"], core: ["Sven"], treasures: ["Crimson Guard"] },
  { enemy: "Bloodseeker", support: ["Abaddon"], core: ["Medusa"], treasures: ["Town Portal Scroll"] },
  { enemy: "Bounty Hunter", support: ["Oracle"], core: ["Slardar"], treasures: ["Lotus Orb"] },
  { enemy: "Brewmaster", support: ["Skywrath Mage"], core: ["Outworld Destroyer"], treasures: ["Orchid Malevolence", "Gleipnir"] },
  { enemy: "Bristleback", support: ["Silencer"], core: ["Viper"], treasures: ["Medallion of Courage", "Solar Crest"] },
  { enemy: "Broodmother", support: ["Grimstroke"], core: ["Earthshaker"], treasures: ["Crimson Guard", "Maelstrom"] },
  { enemy: "Centaur Warrunner", support: ["Underlord"], core: ["Lifestealer"], treasures: ["Spirit Vessel"] },
  { enemy: "Chaos Knight", support: ["Winter Wyvern"], core: ["Sand King"], treasures: ["Shiva's Guard"] },
  { enemy: "Chen", support: ["Enchantress"], core: ["Clinkz"], treasures: ["Hand of Midas"] },
  { enemy: "Clinkz", support: ["Bane"], core: ["Spectre"], treasures: ["Ghost Scepter", "Crimson Guard"] },
  { enemy: "Clockwerk", support: ["Abaddon"], core: ["Lifestealer"], treasures: ["Force Staff"] },
  { enemy: "Crystal Maiden", support: ["Rubick"], core: ["Lifestealer"], treasures: ["Black King Bar", "Orchid Malevolence"] },
  { enemy: "Dark Seer", support: ["Oracle"], core: ["Anti-Mage"], treasures: ["Nullifier"] },
  { enemy: "Dark Willow", support: ["Silencer"], core: ["Axe"], treasures: ["Black King Bar"] },
  { enemy: "Dawnbreaker", support: ["Nyx Assassin"], core: ["Lifestealer"], treasures: ["Spirit Vessel", "Eye of Skadi"] },
  { enemy: "Dazzle", support: ["Ancient Apparition"], core: ["Axe"], treasures: ["Nullifier"] },
  { enemy: "Death Prophet", support: ["Ancient Apparition"], core: ["Bloodseeker"], treasures: ["Eye of Skadi", "Spirit Vessel"] },
  { enemy: "Disruptor", support: ["Abaddon"], core: ["Pangolier"], treasures: ["Black King Bar"] },
  { enemy: "Doom", support: ["Oracle"], core: ["Medusa"], treasures: ["Linken's Sphere"] },
  { enemy: "Dragon Knight", support: ["Elder Titan"], core: ["Viper"], treasures: ["Silver Edge"] },
  { enemy: "Drow Ranger", support: ["Clockwerk"], core: ["Spirit Breaker"], treasures: ["Blink Dagger", "Ghost Scepter"] },
  { enemy: "Earth Spirit", support: ["Silencer"], core: ["Bloodseeker"], treasures: ["Black King Bar"] },
  { enemy: "Earthshaker", support: ["Disruptor"], core: ["Templar Assassin"], treasures: ["Black King Bar", "Force Staff"] },
  { enemy: "Elder Titan", support: ["Shadow Shaman"], core: ["Lifestealer"], treasures: ["Black King Bar", "Force Staff"] },
  { enemy: "Ember Spirit", support: ["Disruptor"], core: ["Slark"], treasures: ["Orchid Malevolence"] },
  { enemy: "Enchantress", support: ["Shadow Demon"], core: ["Marci"], treasures: ["Silver Edge", "Black King Bar"] },
  { enemy: "Enigma", support: ["Silencer"], core: ["Sniper"], treasures: ["Aeon Disk"] },
  { enemy: "Faceless Void", support: ["Shadow Demon"], core: ["Naga Siren"], treasures: ["Aeon Disk", "Eul's Scepter of Divinity"] },
  { enemy: "Grimstroke", support: ["Abaddon"], core: ["Phantom Lancer"], treasures: ["Lotus Orb", "Black King Bar"] },
  { enemy: "Gyrocopter", support: ["Ancient Apparition"], core: ["Faceless Void"], treasures: ["Ghost Scepter", "Heaven's Halberd"] },
  { enemy: "Hoodwink", support: ["Spirit Breaker"], core: ["Timbersaw"], treasures: ["Force Staff"] },
  { enemy: "Huskar", support: ["Ancient Apparition"], core: ["Necrophos"], treasures: ["Spirit Vessel", "Heaven's Halberd"] },
  { enemy: "Invoker", support: ["Silencer"], core: ["Riki"], treasures: ["Black King Bar", "Orchid Malevolence"] },
  { enemy: "Io", support: ["Ancient Apparition"], core: ["Troll Warlord"], treasures: ["Nullifier", "Spirit Vessel"] },
  { enemy: "Jakiro", support: ["Rubick"], core: ["Lifestealer"], treasures: ["Black King Bar", "Force Staff"] },
  { enemy: "Juggernaut", support: ["Shadow Demon"], core: ["Riki"], treasures: ["Black King Bar", "Ghost Scepter"] },
  { enemy: "Keeper of the Light", support: ["Nyx Assassin"], core: ["Night Stalker"], treasures: ["Orchid Malevolence", "Gleipnir"] },
  { enemy: "Kaze", support: ["Winter Wyvern"], core: ["Axe"], treasures: ["Silver Edge", "Ghost Scepter"] },
  { enemy: "Kunkka", support: ["Shadow Demon"], core: ["Lifestealer"], treasures: ["Black King Bar", "Eul's Scepter of Divinity"] },
  { enemy: "Legion Commander", support: ["Oracle"], core: ["Wraith King"], treasures: ["Linken's Sphere", "Lotus Orb"] },
  { enemy: "Leshrac", support: ["Ancient Apparition"], core: ["Anti-Mage"], treasures: ["Blade Mail"] },
  { enemy: "Lich", support: ["Oracle"], core: ["Bristleback"], treasures: ["Black King Bar", "Force Staff"] },
  { enemy: "Lifestealer", support: ["Viper"], core: ["Morphling"], treasures: ["Ghost Scepter", "Heaven's Halberd"] },
  { enemy: "Lina", support: ["Nyx Assassin"], core: ["Anti-Mage"], treasures: ["Black King Bar", "Aeon Disk"] },
  { enemy: "Lion", support: ["Silencer"], core: ["Anti-Mage"], treasures: ["Linken's Sphere", "Lotus Orb"] },
  { enemy: "Lone Druid", support: ["Winter Wyvern"], core: ["Slark"], treasures: ["Ghost Scepter", "Heaven's Halberd"] },
  { enemy: "Luna", support: ["Underlord"], core: ["Phantom Lancer"], treasures: ["Crimson Guard", "Blade Mail"] },
  { enemy: "Lycan", support: ["Winter Wyvern"], core: ["Earthshaker"], treasures: ["Crimson Guard", "Ghost Scepter"] },
  { enemy: "Magnus", support: ["Rubick"], core: ["Sniper"], treasures: ["Aeon Disk", "Black King Bar"] },
  { enemy: "Marci", support: ["Winter Wyvern"], core: ["Axe"], treasures: ["Ghost Scepter", "Heaven's Halberd"] },
  { enemy: "Mars", support: ["Viper"], core: ["Lifestealer"], treasures: ["Silver Edge", "Black King Bar"] },
  { enemy: "Medusa", support: ["Nyx Assassin"], core: ["Anti-Mage"], treasures: ["Diffusal Blade", "Eye of Skadi"] },
  { enemy: "Meepo", support: ["Winter Wyvern"], core: ["Sand King"], treasures: ["Shiva's Guard", "Gleipnir"] },
  { enemy: "Mirana", support: ["Bounty Hunter"], core: ["Night Stalker"], treasures: ["Dust of Appearance", "Orchid Malevolence"] },
  { enemy: "Monkey King", support: ["Viper"], core: ["Timbersaw"], treasures: ["Ghost Scepter", "Force Staff"] },
  { enemy: "Morphling", support: ["Ancient Apparition"], core: ["Anti-Mage"], treasures: ["Orchid Malevolence", "Spirit Vessel"] },
  { enemy: "Muerta", support: ["Shadow Shaman"], core: ["Lifestealer"], treasures: ["Black King Bar", "Nullifier"] },
  { enemy: "Naga Siren", support: ["Winter Wyvern"], core: ["Sand King"], treasures: ["Shiva's Guard"] },
  { enemy: "Nature's Prophet", support: ["Spirit Breaker"], core: ["Timbersaw"], treasures: ["Force Staff"] },
  { enemy: "Necrophos", support: ["Ancient Apparition"], core: ["Anti-Mage"], treasures: ["Nullifier", "Dagon"] },
  { enemy: "Night Stalker", support: ["Viper"], core: ["Lifestealer"], treasures: ["Ghost Scepter", "Force Staff"] },
  { enemy: "Nyx Assassin", support: ["Abaddon"], core: ["Lifestealer"], treasures: ["Sentry Wards", "Gem of True Sight"] },
  { enemy: "Ogre Magi", support: ["Oracle"], core: ["Anti-Mage"], treasures: ["Black King Bar", "Lotus Orb"] },
  { enemy: "Omniknight", support: ["Oracle"], core: ["Shadow Fiend"], treasures: ["Nullifier"] },
  { enemy: "Oracle", support: ["Axe"], core: ["Phantom Assassin"], treasures: ["Nullifier"] },
  { enemy: "Outworld Destroyer", support: ["Nyx Assassin"], core: ["Sniper"], treasures: ["Black King Bar", "Linken's Sphere"] },
  { enemy: "Pangolier", support: ["Grimstroke"], core: ["Bloodseeker"], treasures: ["Gleipnir", "Orchid Malevolence"] },
  { enemy: "Phantom Assassin", support: ["Viper"], core: ["Morphling"], treasures: ["Monkey King Bar", "Blade Mail"] },
  { enemy: "Phantom Lancer", support: ["Lich"], core: ["Earthshaker"], treasures: ["Maelstrom", "Shiva's Guard"] },
  { enemy: "Phoenix", support: ["Snapfire"], core: ["Troll Warlord"], treasures: ["Black King Bar", "Blade Mail"] },
  { enemy: "Primal Beast", support: ["Nyx Assassin"], core: ["Lifestealer"], treasures: ["Black King Bar"] },
  { enemy: "Puck", support: ["Silencer"], core: ["Riki"], treasures: ["Gleipnir", "Orchid Malevolence"] },
  { enemy: "Pudge", support: ["Bane"], core: ["Lifestealer"], treasures: ["Spirit Vessel"] },
  { enemy: "Pugna", support: ["Nyx Assassin"], core: ["Anti-Mage"], treasures: ["Black King Bar"] },
  { enemy: "Queen of Pain", support: ["Silencer"], core: ["Spirit Breaker"], treasures: ["Black King Bar"] },
  { enemy: "Razor", support: ["Oracle"], core: ["Weaver"], treasures: ["Force Staff", "Heaven's Halberd"] },
  { enemy: "Riki", support: ["Disruptor"], core: ["Bristleback"], treasures: ["Force Staff", "Ghost Scepter"] },
  { enemy: "Ringmaster", support: ["Silencer"], core: ["Lifestealer"], treasures: ["Black King Bar", "Orchid Malevolence"] },
  { enemy: "Rubick", support: ["Silencer"], core: ["Riki"], treasures: ["Black King Bar"] },
  { enemy: "Sand King", support: ["Zeus"], core: ["Lifestealer"], treasures: ["Black King Bar", "Pipe of Insight"] },
  { enemy: "Shadow Demon", support: ["Oracle"], core: ["Phantom Lancer"], treasures: ["Black King Bar"] },
  { enemy: "Shadow Fiend", support: ["Nyx Assassin"], core: ["Templar Assassin"], treasures: ["Black King Bar", "Aeon Disk"] },
  { enemy: "Shadow Shaman", support: ["Abaddon"], core: [], treasures: ["Linken's Sphere", "Lotus Orb"] },
  { enemy: "Silencer", support: ["Abaddon"], core: ["Phantom Lancer"], treasures: ["Manta Style"] },
  { enemy: "Skywrath Mage", support: ["Nyx Assassin"], core: ["Pugna"], treasures: ["Black King Bar", "Blade Mail"] },
  { enemy: "Slardar", support: ["Dazzle"], core: ["Troll Warlord"], treasures: ["Ghost Scepter", "Lotus Orb"] },
  { enemy: "Slark", support: ["Disruptor"], core: ["Bloodseeker"], treasures: ["Ghost Scepter", "Orchid Malevolence"] },
  { enemy: "Snapfire", support: ["Abaddon"], core: ["Lifestealer"], treasures: ["Black King Bar", "Blade Mail"] },
  { enemy: "Sniper", support: ["Clockwerk"], core: ["Spirit Breaker"], treasures: ["Blink Dagger", "Ghost Scepter"] },
  { enemy: "Spectre", support: ["Undying"], core: ["Viper"], treasures: ["Silver Edge", "Spirit Vessel"] },
  { enemy: "Spirit Breaker", support: ["Clockwerk"], core: ["Bloodseeker"], treasures: ["Eul's Scepter of Divinity", "Linken's Sphere"] },
  { enemy: "Storm Spirit", support: ["Silencer"], core: ["Anti-Mage"], treasures: ["Orchid Malevolence", "Gleipnir"] },
  { enemy: "Sven", support: ["Shadow Demon"], core: ["Troll Warlord"], treasures: ["Ghost Scepter", "Heaven's Halberd"] },
  { enemy: "Techies", support: ["Zeus"], core: ["Lifestealer"], treasures: ["Black King Bar"] },
  { enemy: "Templar Assassin", support: ["Jakiro"], core: ["Viper"], treasures: ["Radiance"] },
  { enemy: "Terrorblade", support: ["Winter Wyvern"], core: ["Axe"], treasures: ["Shiva's Guard", "Gleipnir"] },
  { enemy: "Tidehunter", support: ["Viper"], core: [], treasures: ["Silver Edge", "Black King Bar"] },
  { enemy: "Timbersaw", support: ["Ancient Apparition"], core: ["Ursa"], treasures: ["Silver Edge", "Spirit Vessel"] },
  { enemy: "Tinker", support: ["Nyx Assassin"], core: ["Night Stalker"], treasures: ["Blink Dagger", "Orchid Malevolence"] },
  { enemy: "Tiny", support: ["Jakiro"], core: ["Slardar"], treasures: ["Aeon Disk"] },
  { enemy: "Treant Protector", support: ["Jakiro"], core: ["Timbersaw"], treasures: ["Force Staff"] },
  { enemy: "Troll Warlord", support: ["Winter Wyvern"], core: ["Axe"], treasures: ["Ghost Scepter", "Heaven's Halberd"] },
  { enemy: "Tusk", support: ["Abaddon"], core: ["Lifestealer"], treasures: ["Ghost Scepter", "Force Staff"] },
  { enemy: "Underlord", support: ["Disruptor"], core: ["Outworld Destroyer"], treasures: ["Silver Edge", "Black King Bar"] },
  { enemy: "Undying", support: ["Snapfire"], core: ["Sniper"], treasures: ["Crimson Guard"] },
  { enemy: "Ursa", support: ["Bane"], core: ["Troll Warlord"], treasures: ["Ghost Scepter", "Heaven's Halberd"] },
  { enemy: "Vengeful Spirit", support: ["Abaddon"], core: ["Phantom Lancer"], treasures: ["Linken's Sphere", "Lotus Orb"] },
  { enemy: "Venomancer", support: ["Oracle"], core: ["Lifestealer"], treasures: ["Pipe of Insight", "Black King Bar"] },
  { enemy: "Viper", support: ["Shadow Demon"], core: ["Chaos Knight"], treasures: ["Black King Bar", "Force Staff"] },
  { enemy: "Visage", support: ["Winter Wyvern"], core: ["Axe"], treasures: ["Crimson Guard", "Maelstrom"] },
  { enemy: "Void Spirit", support: ["Silencer"], core: ["Riki"], treasures: ["Gleipnir", "Orchid Malevolence"] },
  { enemy: "Warlock", support: ["Silencer"], core: ["Weaver"], treasures: ["Diffusal Blade", "Black King Bar"] },
  { enemy: "Weaver", support: ["Disruptor"], core: ["Bloodseeker"], treasures: ["Orchid Malevolence"] },
  { enemy: "Windranger", support: ["Shadow Demon"], core: ["Centaur Warrunner"], treasures: ["Monkey King Bar", "Nullifier"] },
  { enemy: "Winter Wyvern", support: ["Clockwerk"], core: ["Timbersaw"], treasures: ["Black King Bar"] },
  { enemy: "Witch Doctor", support: ["Silencer"], core: ["Night Stalker"], treasures: ["Black King Bar", "Orchid Malevolence"] },
  { enemy: "Wraith King", support: ["Lion"], core: ["Anti-Mage"], treasures: ["Diffusal Blade", "Spirit Vessel"] },
  { enemy: "Zeus", support: ["Silencer"], core: ["Storm Spirit"], treasures: ["Black King Bar", "Pipe of Insight"] },
];

export const HERO_NAMES = DOTA_DATA.map(({ enemy }) => enemy);
